### ISSUE TITLE
Backside connections

### ISSUE THREAD

**Issue by freyk** [jonataubert/RLOD_B2XR#1]
I seen your steps and I found the alter project by @lle https://github.com/lle/boostedBattery/blob/master/debugConn.md, and I see in the back side of the board some connectors maybe you can use the MCLR without the connection of both MCRL + GND. I'm not electronic engineer guy I just make me sense and some ideas about every steps that I watched in both tutorials. I hope that help to you.

**Comment by jonataubert** [comment]
Hi freyk, 
Thanks for your feedback, it makes sense to show other ways of connecting things.
It seems soldering is the most difficult part of the job for most people. I currently don't have a simple solution for the SPI flash but the MCLR to GND can be greatly simplified using the proper connector (TC2030-IDC) which is now mentioned in the procedure.

Best,
